#!/usr/bin/env ruby
require "thor"

class SubCommandBase < Thor
  def self.banner(command, namespace = nil, subcommand = false)
    "#{basename} #{subcommand_prefix} #{command.usage}"
  end

  def self.subcommand_prefix
    self.name.gsub(%r{.*::}, '').gsub(%r{^[A-Z]}) { |match| match[0].downcase }.gsub(%r{[A-Z]}) { |match| "-#{match[0].downcase}" }
  end
end

module App
  class Files < SubCommandBase
    desc "list <path>", "list files in path"
    def list(path)
      # list
      puts "listing files in path: #{path}"
    end

    desc "sanitize", "sanitize files"
    def sanitize
      # sanitize
    end
  end

  class CLI < Thor
    desc "files", "list and sanitize files"
    subcommand "files", Files
  end
end

App::CLI.start


